[workspace]
resolver = "3"
members = [
    "capdows",
    "controls",
    "example", 
    "macros",
    "res"
]
[workspace.package]
authors = ["slyfhuy68(github.com)"]
version = "0.0.1"
license = "MIT OR Apache-2.0"
edition = "2024"
