[package]
name = "capdows_macros"
authors.workspace = true
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
[lib]
proc-macro = true
